development:
  adapter: postgresql
  encoding: unicode
  database: yt_dev
  pool: 5
  username: yt_user
  password: youtube

test:
  adapter: postgresql
  encoding: unicode
  database: yt_test
  pool: 5
  username: yt_user
  password: youtube